import type { Asset, WorkOrder } from '../types';

export const seedMockData = () => {
  const currentAssets = localStorage.getItem('cf_assets');
  const needsReseed = !currentAssets || currentAssets.includes('Radiology') || currentAssets.includes('MRI');
  if (needsReseed) {
    localStorage.removeItem('cf_assets');
    localStorage.removeItem('cf_workorders');
  }

  // 1. Seed Assets (mapping from mockEquipment with additional fields)
  if (!localStorage.getItem('cf_assets')) {
    const initialAssets: Asset[] = [
      {
        id: 'EQ-FC-001',
        name: 'HIFU 7D machine',
        status: 'operational',
        uptime: 99.4,
        healthScore: 98,
        lastService: '2026-05-10',
        nextService: '2026-11-10',
        location: 'Facial Care Room A',
        department: 'Facial Contouring',
        serialNumber: 'HF-7D-2026A',
        model: 'HIFU 7D',
        manufacturer: 'Classys',
        purchaseDate: '2025-01-15',
        workOrderCount: 0,
        assignedTech: 'Elena Rostova',
      },
      {
        id: 'EQ-FC-002',
        name: 'Ultra F (Ultra HIFU) machine',
        status: 'critical',
        uptime: 94.2,
        healthScore: 68,
        lastService: '2026-05-15',
        nextService: '2026-11-15',
        location: 'Therapy Room 3',
        department: 'Facial Contouring',
        serialNumber: 'UF-HIFU-8822B',
        model: 'Ultra F',
        manufacturer: 'Ultra F Co.',
        purchaseDate: '2024-03-10',
        workOrderCount: 1,
        assignedTech: 'Marcus Vance',
      },
      {
        id: 'EQ-FC-003',
        name: 'RF 5D machine',
        status: 'pending',
        uptime: 98.1,
        healthScore: 84,
        lastService: '2026-06-01',
        nextService: '2026-12-01',
        location: 'VIP Treatment Suite',
        department: 'Facial Contouring',
        serialNumber: 'RF-5D-5522X',
        model: 'RF 5D',
        manufacturer: 'Thermage',
        purchaseDate: '2024-11-20',
        workOrderCount: 1,
        assignedTech: 'Elena Rostova',
      },
      {
        id: 'EQ-SC-001',
        name: 'Q-Switch Laser machine',
        status: 'maintenance',
        uptime: 97.8,
        healthScore: 78,
        lastService: '2026-06-05',
        nextService: '2026-09-05',
        location: 'Laser Room 1',
        department: 'Skincare',
        serialNumber: 'QS-LSR-9922Z',
        model: 'Spectra XT',
        manufacturer: 'Lutronic',
        purchaseDate: '2023-08-20',
        workOrderCount: 1,
        assignedTech: 'Sarah Chen',
      },
      {
        id: 'EQ-SC-002',
        name: 'Diode Laser machine',
        status: 'operational',
        uptime: 99.6,
        healthScore: 96,
        lastService: '2026-05-20',
        nextService: '2026-11-20',
        location: 'Laser Room 2',
        department: 'Skincare',
        serialNumber: 'DD-LSR-3304Y',
        model: 'Soprano Titanium',
        manufacturer: 'Alma Lasers',
        purchaseDate: '2025-02-15',
        workOrderCount: 1,
        assignedTech: 'Elena Rostova',
      },
      {
        id: 'EQ-SC-003',
        name: 'Supersonic Vitamin Infusion machine',
        status: 'operational',
        uptime: 98.9,
        healthScore: 92,
        lastService: '2026-06-09',
        nextService: '2026-12-09',
        location: 'Skin Treatment Bed 4',
        department: 'Skincare',
        serialNumber: 'SS-VIT-0284W',
        model: 'Supersonic 3000',
        manufacturer: 'Sonocare',
        purchaseDate: '2024-10-05',
        workOrderCount: 1,
        assignedTech: 'Marcus Vance',
      },
      {
        id: 'EQ-SC-004',
        name: 'BIOLIGHT Light Therapy machine',
        status: 'operational',
        uptime: 99.7,
        healthScore: 99,
        lastService: '2026-06-02',
        nextService: '2026-12-02',
        location: 'Therapy Room 5',
        department: 'Skincare',
        serialNumber: 'BL-LGT-7722V',
        model: 'Biolight 500',
        manufacturer: 'BioLight',
        purchaseDate: '2025-03-01',
        workOrderCount: 0,
        assignedTech: 'Sarah Chen',
      },
      {
        id: 'EQ-BF-001',
        name: 'G5 Fat Reduction Massage machine',
        status: 'operational',
        uptime: 98.0,
        healthScore: 90,
        lastService: '2026-05-25',
        nextService: '2026-11-25',
        location: 'Body Contouring Room B',
        department: 'Body Firming',
        serialNumber: 'G5-FAT-5511U',
        model: 'G5 Studio',
        manufacturer: 'G5 Brand',
        purchaseDate: '2024-05-18',
        workOrderCount: 0,
        assignedTech: 'Marcus Vance',
      },
    ];
    localStorage.setItem('cf_assets', JSON.stringify(initialAssets));
  }

  // 2. Seed Work Orders (mapping from mockTickets with statuses)
  if (!localStorage.getItem('cf_workorders')) {
    const initialWorkOrders: WorkOrder[] = [
      {
        id: 'TK-2847',
        title: 'Transducer crystal array overheating & power warning',
        description: 'System reporting transducer crystal array overheating warnings and power fluctuations during activation. Transducer coupling gel sensor error.',
        assetId: 'EQ-FC-002',
        assetName: 'Ultra F (Ultra HIFU) machine',
        location: 'Therapy Room 3',
        status: 'assigned',
        priority: 'critical',
        assignedTo: 'Marcus Vance',
        category: 'Hardware Failure',
        openedAt: '2026-06-10T08:30:00Z',
        updatedAt: '2026-06-10T10:45:00Z',
        slaDeadline: '2026-06-10T12:30:00Z',
        progress: 45,
        checklist: [
          { id: 'chk-1', text: 'Verify transducer signal connections and power voltage lines', checked: true },
          { id: 'chk-2', text: 'Inspect applicator handpiece and contact coupling pin', checked: true },
          { id: 'chk-3', text: 'Run rf transmitter / pulse calibration tests', checked: false },
          { id: 'chk-4', text: 'Measure cooling system fan impedance and thermocouple offset', checked: false },
          { id: 'chk-5', text: 'Document transducer energy output and sign off logbook', checked: false },
        ],
        timeline: [
          {
            id: 't-1',
            action: 'System reported transducer overheat warning & coupling alert',
            by: 'System Telemetry',
            time: '2026-06-10T08:30:00Z',
            color: 'critical',
          },
          {
            id: 't-2',
            action: 'Ticket dispatched and assigned to Lead Engineer',
            by: 'Dispatch Automated System',
            time: '2026-06-10T08:35:00Z',
            color: 'info',
          },
          {
            id: 't-3',
            action: 'On-site investigation initialized, system placed in offline state',
            by: 'Marcus Vance',
            time: '2026-06-10T09:15:00Z',
            color: 'warning',
          },
          {
            id: 't-4',
            action: 'Manufacturer support contacted for replacement transducer array module',
            by: 'Marcus Vance',
            time: '2026-06-10T10:45:00Z',
            color: 'info',
          },
        ],
      },
      {
        id: 'TK-9582',
        title: 'Electrode pin wear & intermittent handpiece contact',
        description: 'RF handpiece electrode pins showing wear and intermittent contact warning on control screen. Electrode replacement recommended.',
        assetId: 'EQ-FC-003',
        assetName: 'RF 5D machine',
        location: 'VIP Treatment Suite',
        status: 'in_progress',
        priority: 'high',
        assignedTo: 'Elena Rostova',
        category: 'Power Supply',
        openedAt: '2026-06-11T07:15:00Z',
        updatedAt: '2026-06-11T07:15:00Z',
        slaDeadline: '2026-06-11T15:15:00Z',
        progress: 15,
        checklist: [
          { id: 'chk-1', text: 'Inspect and clean applicator socket pins', checked: false },
          { id: 'chk-2', text: 'Verify sensor calibration and energy feedback rails', checked: false },
          { id: 'chk-3', text: 'Run diagnostics check and self-test suite', checked: false },
          { id: 'chk-4', text: 'Document results and sign off equipment log', checked: false },
        ],
        timeline: [
          {
            id: 't-1',
            action: 'Intermittent handpiece connection alert received',
            by: 'System Telemetry',
            time: '2026-06-11T07:15:00Z',
            color: 'warning',
          },
        ],
      },
      {
        id: 'TK-1204',
        title: '6-Month Calibration and Optics Cleaning',
        description: 'Scheduled 6-month calibration and laser output power verification. Check handpiece fiber condition and flashlamp trigger voltage.',
        assetId: 'EQ-SC-001',
        assetName: 'Q-Switch Laser machine',
        location: 'Laser Room 1',
        status: 'in_progress',
        priority: 'normal',
        assignedTo: 'Sarah Chen',
        category: 'Routine PM',
        openedAt: '2026-06-11T06:00:00Z',
        updatedAt: '2026-06-11T06:00:00Z',
        slaDeadline: '2026-06-12T06:00:00Z',
        progress: 75,
        checklist: [
          { id: 'chk-1', text: 'Inspect laser output energy levels', checked: true },
          { id: 'chk-2', text: 'Calibrate optics beam alignment deviation', checked: true },
          { id: 'chk-3', text: 'Clean protective window lens elements', checked: true },
          { id: 'chk-4', text: 'Run electric safety checks', checked: false },
        ],
        timeline: [
          {
            id: 't-1',
            action: 'PM work order generated automatically',
            by: 'PM Scheduler System',
            time: '2026-06-11T06:00:00Z',
            color: 'info',
          },
        ],
      },
      {
        id: 'TK-4839',
        title: 'Verify software patch installation',
        description: 'Error code 402 showing on startup. Cleared with system reset but needs software patch verification to prevent recurrence.',
        assetId: 'EQ-SC-002',
        assetName: 'Diode Laser machine',
        location: 'Laser Room 2',
        status: 'completed',
        priority: 'low',
        assignedTo: 'Elena Rostova',
        category: 'Software Issue',
        openedAt: '2026-06-10T14:20:00Z',
        updatedAt: '2026-06-11T14:20:00Z',
        slaDeadline: '2026-06-11T14:20:00Z',
        progress: 100,
        checklist: [],
        timeline: [],
      },
      {
        id: 'TK-3394',
        title: 'Ultrasound head recalibration',
        description: 'Ultrasound head transducer recalibrated. Signal amplifier output adjusted and safety limit switch verified.',
        assetId: 'EQ-SC-003',
        assetName: 'Supersonic Vitamin Infusion machine',
        location: 'Skin Treatment Bed 4',
        status: 'closed',
        priority: 'normal',
        assignedTo: 'Marcus Vance',
        category: 'Calibration',
        openedAt: '2026-06-10T09:00:00Z',
        updatedAt: '2026-06-11T09:00:00Z',
        slaDeadline: '2026-06-11T09:00:00Z',
        progress: 100,
        checklist: [],
        timeline: [],
      },
    ];
    localStorage.setItem('cf_workorders', JSON.stringify(initialWorkOrders));
  }
};

