import type { Asset, WorkOrder } from '../types';

export const seedMockData = () => {
  // 1. Seed Assets (mapping from mockEquipment with additional fields)
  if (!localStorage.getItem('cf_assets')) {
    const initialAssets: Asset[] = [
      {
        id: 'EQ-MRI-8822',
        name: 'GE Signa 3T MRI Scanner',
        status: 'critical',
        uptime: 94.2,
        healthScore: 68,
        lastService: '2026-05-15',
        nextService: '2026-11-15',
        location: 'Imaging Center - Room 3',
        department: 'Radiology',
        serialNumber: 'GE-SIG-998822A',
        model: 'Signa 3T',
        manufacturer: 'GE HealthCare',
        purchaseDate: '2022-03-10',
        workOrderCount: 14,
        assignedTech: 'Marcus Vance',
      },
      {
        id: 'EQ-DEF-1049',
        name: 'Philips Tempus LS Defibrillator',
        status: 'pending',
        uptime: 99.1,
        healthScore: 84,
        lastService: '2026-06-01',
        nextService: '2026-12-01',
        location: 'Emergency Department - ER-B',
        department: 'Cardiology',
        serialNumber: 'PH-TMP-1049X',
        model: 'Tempus LS',
        manufacturer: 'Philips Medical',
        purchaseDate: '2023-05-14',
        workOrderCount: 8,
        assignedTech: 'Elena Rostova',
      },
      {
        id: 'EQ-VEN-5021',
        name: 'Dräger Evita V500 Ventilator',
        status: 'maintenance',
        uptime: 97.8,
        healthScore: 78,
        lastService: '2026-06-05',
        nextService: '2026-09-05',
        location: 'Intensive Care Unit - Bed 14',
        department: 'ICU',
        serialNumber: 'DG-EVT-5021Z',
        model: 'Evita V500',
        manufacturer: 'Drägerwerk AG',
        purchaseDate: '2021-08-20',
        workOrderCount: 12,
        assignedTech: 'Sarah Chen',
      },
      {
        id: 'EQ-INF-3304',
        name: 'Baxter Sigma Spectrum Infusion Pump',
        status: 'operational',
        uptime: 99.6,
        healthScore: 96,
        lastService: '2026-05-20',
        nextService: '2026-11-20',
        location: 'Pediatrics Ward - Room 204',
        department: 'Pediatrics',
        serialNumber: 'BX-SGM-3304B',
        model: 'Sigma Spectrum',
        manufacturer: 'Baxter International',
        purchaseDate: '2024-01-15',
        workOrderCount: 3,
        assignedTech: 'Elena Rostova',
      },
      {
        id: 'EQ-MON-0284',
        name: 'Mindray BeneVision N22 Patient Monitor',
        status: 'operational',
        uptime: 98.9,
        healthScore: 92,
        lastService: '2026-06-09',
        nextService: '2026-12-09',
        location: 'Cardiac Care Unit - CCU-4',
        department: 'Cardiology',
        serialNumber: 'MR-BVIS-0284P',
        model: 'BeneVision N22',
        manufacturer: 'Mindray Medical',
        purchaseDate: '2023-10-05',
        workOrderCount: 5,
        assignedTech: 'Marcus Vance',
      },
    ];
    localStorage.setItem('cf_assets', JSON.stringify(initialAssets));
  }

  // 2. Seed Work Orders (mapping from mockTickets with statuses)
  if (!localStorage.getItem('cf_workorders')) {
    const initialWorkOrders: WorkOrder[] = [
      {
        id: 'TK-2847',
        title: 'Liquid helium level low warning & temperature spikes',
        description: 'Liquid helium level has dropped below critical threshold. System reporting gradient coil temperature warnings and automatic shutdown will trigger if pressure increases further.',
        assetId: 'EQ-MRI-8822',
        assetName: 'GE Signa 3T MRI Scanner',
        location: 'Imaging Center - Room 3',
        status: 'assigned', // Map 'critical' ticket status to 'assigned' workorder status
        priority: 'critical',
        assignedTo: 'Marcus Vance',
        category: 'Hardware Failure',
        openedAt: '2026-06-10T08:30:00Z',
        updatedAt: '2026-06-10T10:45:00Z',
        slaDeadline: '2026-06-10T12:30:00Z',
        progress: 45,
        checklist: [
          { id: 'chk-1', text: 'Verify helium pressure levels and temperature monitors', checked: true },
          { id: 'chk-2', text: 'Inspect cryostat vent valves and safety burst discs', checked: true },
          { id: 'chk-3', text: 'Run rf transmitter calibration tests', checked: false },
          { id: 'chk-4', text: 'Measure gradient coil impedance and insulation resistance', checked: false },
          { id: 'chk-5', text: 'Document helium boil-off rate and log calibration logbook', checked: false },
        ],
        timeline: [
          {
            id: 't-1',
            action: 'System reported helium level low warning & pressure spike auto-alert',
            by: 'System Telemetry',
            time: '2026-06-10T08:30:00Z',
            color: 'critical',
          },
          {
            id: 't-2',
            action: 'Ticket dispatched and assigned to Lead Engineer',
            by: 'Dispatch Automated System',
            time: '2026-06-10T08:35:00Z',
            color: 'info',
          },
          {
            id: 't-3',
            action: 'On-site investigation initialized, system placed in offline state',
            by: 'Marcus Vance',
            time: '2026-06-10T09:15:00Z',
            color: 'warning',
          },
          {
            id: 't-4',
            action: 'Helium recharge provider contacted for emergency refill delivery',
            by: 'Marcus Vance',
            time: '2026-06-10T10:45:00Z',
            color: 'info',
          },
        ],
      },
      {
        id: 'TK-9582',
        title: 'Internal cell battery replacement',
        description: 'Battery failing to hold charge for more than 10 minutes. Requires immediate replacement of internal cell pack and recalibration of discharge sequence.',
        assetId: 'EQ-DEF-1049',
        assetName: 'Philips Tempus LS Defibrillator',
        location: 'Emergency Department - ER-B',
        status: 'in_progress', // Map 'pending' ticket to 'in_progress' workorder status
        priority: 'high',
        assignedTo: 'Elena Rostova',
        category: 'Power Supply',
        openedAt: '2026-06-11T07:15:00Z',
        updatedAt: '2026-06-11T07:15:00Z',
        slaDeadline: '2026-06-11T15:15:00Z',
        progress: 15,
        checklist: [
          { id: 'chk-1', text: 'Inspect and clean electrical components', checked: false },
          { id: 'chk-2', text: 'Verify sensor calibration and power rails', checked: false },
          { id: 'chk-3', text: 'Run diagnostics check and self-test suite', checked: false },
          { id: 'chk-4', text: 'Document results and sign off equipment log', checked: false },
        ],
        timeline: [
          {
            id: 't-1',
            action: 'Low battery telemetry alert received',
            by: 'System Telemetry',
            time: '2026-06-11T07:15:00Z',
            color: 'warning',
          },
        ],
      },
      {
        id: 'TK-1204',
        title: '6-Month Routine PM and Filter Exchange',
        description: 'Scheduled 6-month preventative maintenance and filter exchange. Check oxygen sensor voltage and pressure sensors deviation.',
        assetId: 'EQ-VEN-5021',
        assetName: 'Dräger Evita V500 Ventilator',
        location: 'Intensive Care Unit - Bed 14',
        status: 'in_progress', // Map 'maintenance' ticket status
        priority: 'normal',
        assignedTo: 'Sarah Chen',
        category: 'Routine PM',
        openedAt: '2026-06-11T06:00:00Z',
        updatedAt: '2026-06-11T06:00:00Z',
        slaDeadline: '2026-06-12T06:00:00Z',
        progress: 75,
        checklist: [
          { id: 'chk-1', text: 'Inspect oxygen sensor voltage levels', checked: true },
          { id: 'chk-2', text: 'Calibrate flow and pressure sensors deviation', checked: true },
          { id: 'chk-3', text: 'Replace intake filter element', checked: true },
          { id: 'chk-4', text: 'Run electric safety checks', checked: false },
        ],
        timeline: [
          {
            id: 't-1',
            action: 'PM work order generated automatically',
            by: 'PM Scheduler System',
            time: '2026-06-11T06:00:00Z',
            color: 'info',
          },
        ],
      },
      {
        id: 'TK-4839',
        title: 'Verify software patch installation',
        description: 'Error code 402 showing on startup. Cleared with system reset but needs software patch verification to prevent recurrence.',
        assetId: 'EQ-INF-3304',
        assetName: 'Baxter Sigma Spectrum Infusion Pump',
        location: 'Pediatrics Ward - Room 204',
        status: 'completed',
        priority: 'low',
        assignedTo: 'Elena Rostova',
        category: 'Software Issue',
        openedAt: '2026-06-10T14:20:00Z',
        updatedAt: '2026-06-11T14:20:00Z',
        slaDeadline: '2026-06-11T14:20:00Z',
        progress: 100,
        checklist: [],
        timeline: [],
      },
      {
        id: 'TK-3394',
        title: 'ECG module recalibration',
        description: 'ECG module reporting incorrect waveforms. Recalibrated signal amplifier and verified with simulator. Replaced lead wires.',
        assetId: 'EQ-MON-0284',
        assetName: 'Mindray BeneVision N22 Patient Monitor',
        location: 'Cardiac Care Unit - CCU-4',
        status: 'closed',
        priority: 'normal',
        assignedTo: 'Marcus Vance',
        category: 'Calibration',
        openedAt: '2026-06-10T09:00:00Z',
        updatedAt: '2026-06-11T09:00:00Z',
        slaDeadline: '2026-06-11T09:00:00Z',
        progress: 100,
        checklist: [],
        timeline: [],
      },
    ];
    localStorage.setItem('cf_workorders', JSON.stringify(initialWorkOrders));
  }
};
